"""empty message

Revision ID: ebbbabaad4d5
Revises: d95d256fe7e0
Create Date: 2026-04-10 15:05:15.623124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbbabaad4d5'
down_revision = 'd95d256fe7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('hash_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('hash_password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
